// --- PRESET IMAGES CONFIGURATION ---
export const PRESET_LOCATION_IMAGES = [
  {
    id: "img_home_luxury",
    url: "https://github.com/user-attachments/assets/ac3011dd-5ee0-4278-9ed0-f77184f7f703",
    desc: "A luxury apartment, looks expensive, modern decor, cool tones",
    keywords: "luxury apartment, studio, residence, downtown, floor-to-ceiling windows",
  },
  {
    id: "img_cafe_cozy",
    url: "https://github.com/user-attachments/assets/b2b72afe-0942-4e64-b906-3c81c704547a",
    desc: "A cozy corner of a warm café, with wooden tables and chairs and green plants",
    keywords: "café, afternoon tea, leisure, bookstore, warm",
  },
  {
    id: "img_street_cyber",
    url: "https://github.com/user-attachments/assets/1fbd0490-278d-43c4-b60d-f0e8046b2571",
    desc: "A cyberpunk-style street, neon lights flickering, rainy night",
    keywords: "street, night scene, cyberpunk, downtown, dark",
  },
  {
    id: "img_office_modern",
    url: "https://github.com/user-attachments/assets/703308e8-ca7d-4dd4-a916-3a11b8e8fc48",
    desc: "A modern office, somewhat oppressive, large glass curtain walls",
    keywords: "office, company, meeting room, work, office building",
  },
  {
    id: "img_park_quiet",
    url: "https://github.com/user-attachments/assets/59b90064-8822-44e2-987d-954a42f2da5b",
    desc: "A quiet park bench, surrounded by trees, a good place to space out",
    keywords: "park, nature, rest, bench, outdoors",
  },
  {
    id: "img_sexual_stream",
    url: "https://github.com/user-attachments/assets/2b20015a-cb44-416f-9b2b-ab5164235b2d",
    desc: "A shady adult live-streaming platform",
    keywords: "adult content, live stream, erotic stream",
  },
  {
    id: "img_cocktail_bar",
    url: "https://github.com/user-attachments/assets/54c8b933-a596-4fb0-a4c1-c0827b920aad",
    desc: "A bar with a serene atmosphere",
    keywords: "upscale, bar",
  },
  {
    id: "img_old_street",
    url: "https://github.com/user-attachments/assets/3b48118f-c52d-4109-9546-7fef38f64c44",
    desc: "A street scene in the old residential district of a coastal city",
    keywords: "old district, residential area, street, coastal city, vintage",
  },
  {
    id: "img_tech_company",
    url: "https://github.com/user-attachments/assets/9d50fe02-d5c6-4be6-a6c2-3c2fc4c04684",
    desc: "A tech company hub in the new district",
    keywords: "internet company, tech company, new district, traffic jam, office workers",
  },
  {
    id: "img_city_center",
    url: "https://github.com/user-attachments/assets/626fd109-a115-46b3-bd97-d3f7f26f8a72",
    desc: "Downtown CBD, the most prosperous commercial district in the city",
    keywords: "CBD, commercial district, shopping area, downtown, bustling",
  },
  {
    id: "img_high_end_restaurant",
    url: "https://github.com/user-attachments/assets/91aca5a1-6bee-483a-b171-042a4da3d9f9",
    desc: "A high-end restaurant",
    keywords: "upscale, French cuisine, Western food",
  },
  {
    id: "img_studio",
    url: "https://github.com/user-attachments/assets/d408f807-9348-4de7-8915-2977f166cbea",
    desc: "A studio, suitable for music, design, and other work scenes, with various professional equipment",
    keywords: "work, music, design, equipment, personal studio",
  },
  {
    id: "img_small_apartment",
    url: "https://github.com/user-attachments/assets/2367aa30-af1b-421b-b95b-c8e585a8f06a",
    desc: "A regular rental apartment, with a bed, desk, kitchen, and other common furniture",
    keywords: "rental, apartment, renting",
  },
  {
    id: "img_lab",
    url: "https://github.com/user-attachments/assets/f322b344-ab66-4d0f-aac6-2a0d5a852a84",
    desc: "A laboratory",
    keywords: "high-end, precision instruments, sterile environment, glassware, cool tones, minimalism",
  },
  {
    id: "img_greenhouse",
    url: "https://github.com/user-attachments/assets/010ef494-2ccb-4bdc-b7e2-35cd1694cf18",
    desc: "A private estate greenhouse",
    keywords: "glass dome, rare plants, humid air, earthy scent, green, tranquil, natural light",
  },
  {
    id: "img_hospital",
    url: "https://github.com/user-attachments/assets/18f66252-5f30-4ec3-850c-bb39cccb28c9",
    desc: "A hospital",
    keywords: "harsh white lights, disinfectant smell, IV stand, blue waiting chairs, cold tiles, electronic display",
  },
  {
    id: "img_back_alley",
    url: "https://github.com/user-attachments/assets/3a8a19d7-56e7-42cc-81a4-3bb4fefd8190",
    desc: "A back alley in the old district",
    keywords: "graffiti wall, damp asphalt, puddles, neon reflections, trash cans, stray cats, shadows",
  },
  {
    id: "img_livehouse",
    url: "https://github.com/user-attachments/assets/d59ea2ae-ed98-4f58-aad6-bbb823cd5190",
    desc: "A livehouse, live music venue",
    keywords: "stage lights, heavy bass, smell of sweat, shouting, darkness, laser lights",
  },
  {
    id: "img_repair_shop",
    url: "https://github.com/user-attachments/assets/73170b29-b762-44d5-8586-49038d530f3c",
    desc: "A motorcycle/auto repair shop",
    keywords: "engine oil smell, metal parts, scattered tools, tires, greasy floor, mechanical noise, roller shutter door",
  },
  {
    id: "img_fast_food_shop",
    url: "https://github.com/user-attachments/assets/51025fa5-2a83-4e77-a38e-681143e9717f",
    desc: "A fast food restaurant, fried chicken shop",
    keywords:
      "fried chicken, deep-fried aroma, orange lighting, plastic tables and chairs, greasy floor, noisy chatter, trays, glass door",
  },
  {
    id: "img_old_factory",
    url: "https://github.com/user-attachments/assets/d0b78f2f-e66c-4026-94ae-9002327566a7",
    desc: "Rooftop of an abandoned factory",
    keywords: "rusty railings, vast emptiness, wind, distant city skyline, graffiti wall, gravel, sunset glow",
  },
  {
    id: "img_campus_corner",
    url: "https://github.com/user-attachments/assets/b9ac31c1-b414-42f3-bd8b-8c0419452f63",
    desc: "High school campus rooftop/corner",
    keywords: "chain-link fence, class bell, blue sky, graffiti-covered desk, secret hideout, wind",
  },
  {
    id: "img_night_river",
    url: "https://github.com/user-attachments/assets/7d1fce26-064e-4734-b352-752199a7db5b",
    desc: "Riverside embankment at night",
    keywords: "sound of flowing water, humid air, pebbles, reed marsh, nighttime",
  },
  {
    id: "img_morning_river",
    url: "https://github.com/user-attachments/assets/a2705788-e8ab-4264-9c5d-c02bf99879d3",
    desc: "Riverside embankment during the day",
    keywords: "sound of flowing water, humid air, pebbles, reed marsh, daytime",
  },
  {
    id: "img_villa_public_space",
    url: "https://github.com/user-attachments/assets/19c818a5-78d5-4a7e-8f10-5de11718c8cf",
    desc: "Villa, common living room",
    keywords: "fabric sofa, open space, warm lighting, bright, throw pillows",
  },
  {
    id: "img_interview_room",
    url: "https://github.com/user-attachments/assets/c58a03e9-e4a3-43d3-be14-87a49127ec72",
    desc: "Interview room / solo interview booth",
    keywords: "solid color backdrop, spotlight, camera, single bar stool, soundproof walls",
  },
  {
    id: "img_high_end_seaview_restaurant",
    url: "https://github.com/user-attachments/assets/91aca5a1-6bee-483a-b171-042a4da3d9f9",
    desc: "Ocean-view floor-to-ceiling window restaurant",
    keywords: "long dining table, elegant plating, fresh flowers, ocean view outside the window, candlelight, formal dinner",
  },
  {
    id: "img_supermarket",
    url: "https://github.com/user-attachments/assets/f0a3c620-8f94-4eb4-af6c-4cace2e91d09",
    desc: "Supermarket shopping area",
    keywords: "shopping cart, shelves, daily necessities, groceries, everyday life",
  },
  {
    id: "img_home_theater",
    url: "https://github.com/user-attachments/assets/f1980ad5-ad91-481e-964a-7d8d61e4a851",
    desc: "Media room, movie room, game room",
    keywords: "projector, bean bag sofa, blackout curtains, movie posters, dim lighting, private space",
  },
  {
    id: "img_car",
    url: "https://github.com/user-attachments/assets/9d652563-6328-4213-bc47-0a056a2970dc",
    desc: "Car, interior of a car",
    keywords: "tight space, enclosed environment, navigation screen, car music, scenery along the way",
  },
  {
    id: "img_garden_pool",
    url: "https://github.com/user-attachments/assets/8fd24740-7111-4669-b909-c9609f298a8e",
    desc: "Villa outdoor pool / garden",
    keywords: "villa, resort hotel, lounge chair, ambient light strips, shimmering water, barbecue grill, cool night breeze",
  },
  {
    id: "img_university_1",
    url: "https://github.com/user-attachments/assets/4630e3bb-39e9-4083-a901-f0a054e5716b",
    desc: "University campus 1",
    keywords: "academic building, ginkgo trees, artificial lake",
  },
  {
    id: "img_university_2",
    url: "https://github.com/user-attachments/assets/294533cb-3d8a-46c9-a464-0a76d8d400e6",
    desc: "University campus 2",
    keywords: "academic building, library, cafeteria, cherry blossoms, artificial lake",
  },
  {
    id: "img_high_school_1",
    url: "https://github.com/user-attachments/assets/eecb8594-ae25-4a01-bc25-56bd3f78ea3f",
    desc: "Private high school campus",
    keywords: "academic building, cafeteria, sports field, basketball court",
  },
  {
    id: "img_high_school_2",
    url: "https://github.com/user-attachments/assets/81670664-b6dd-44ce-a9b3-6075bb8bc656",
    desc: "Public high school campus",
    keywords: "national flag, ginkgo trees, academic building, cafeteria, sports field, basketball court",
  },
  {
    id: "img_high_school_2",
    url: "https://github.com/user-attachments/assets/81670664-b6dd-44ce-a9b3-6075bb8bc656",
    desc: "Public high school campus",
    keywords: "national flag, ginkgo trees, academic building, cafeteria, sports field, basketball court",
  },
  {
    id: "img_border_area",
    url: "https://github.com/user-attachments/assets/6f613cf9-5717-4960-8820-445cb498fe16",
    desc: "Border / lawless zone",
    keywords: "lawless, wild, border town, abandoned industrial zone, international waters cruise, tropical rainforest, vice",
  },
  {
    id: "img_office",
    url: "https://files.catbox.moe/czxw29.png",
    desc: "Office desk / workstation",
    keywords: "office building, office, workstation, desk",
  },
  {
    id: "img_villa",
    url: "https://files.catbox.moe/4kobl6.png",
    desc: "Villa interior",
    keywords: "villa, living room, high-end, duplex, floor-to-ceiling windows",
  },
  {
    id: "img_concert",
    url: "https://files.catbox.moe/hns9ir.png",
    desc: "Concert",
    keywords: "concert, performance, band, massive crowd",
  },
  {
    id: "img_ancient_imperial_court",
    url: "https://files.catbox.moe/6pwxwu.png",
    desc: "Ancient Chinese imperial court",
    keywords: "imperial court, court assembly",
  },
  {
    id: "img_ancient_bedroom",
    url: "https://files.catbox.moe/ejfdfp.png",
    desc: "Ancient Chinese royal bedchamber",
    keywords: "royal bedchamber",
  },
  {
    id: "img_museum",
    url: "https://files.catbox.moe/4owk8q.png",
    desc: "Museum",
    keywords: "museum",
  },
  {
    id: "img_art_gallery",
    url: "https://files.catbox.moe/1mmd2f.png",
    desc: "Art gallery",
    keywords: "art gallery",
  },
  {
    id: "img_art_exhibition",
    url: "https://files.catbox.moe/7v1sqz.png",
    desc: "Art exhibition",
    keywords: "art exhibition, painting exhibition, abstract art",
  },
];
