// --- PRESET IMAGES CONFIGURATION ---
export const PRESET_LOCATION_IMAGES = [
  {
    id: "img_home_luxury",
    url: "https://github.com/user-attachments/assets/ac3011dd-5ee0-4278-9ed0-f77184f7f703",
    desc: "一个高端公寓，房租很贵的样子，现代装修，冷色调",
    keywords: "高端公寓, 单身公寓, 住所, 新城区, 落地窗",
  },
  {
    id: "img_cafe_cozy",
    url: "https://github.com/user-attachments/assets/b2b72afe-0942-4e64-b906-3c81c704547a",
    desc: "一个温暖舒适的咖啡馆角落，有木质桌椅和绿植",
    keywords: "咖啡馆, 下午茶, 休闲, 书店, 温暖",
  },
  {
    id: "img_street_cyber",
    url: "https://github.com/user-attachments/assets/1fbd0490-278d-43c4-b60d-f0e8046b2571",
    desc: "赛博朋克风格的街道，霓虹灯闪烁，雨夜",
    keywords: "街道, 夜景, 赛博朋克, 闹市区, 阴暗",
  },
  {
    id: "img_office_modern",
    url: "https://github.com/user-attachments/assets/703308e8-ca7d-4dd4-a916-3a11b8e8fc48",
    desc: "现代化的办公室，甚至有点压抑，大面积的玻璃幕墙",
    keywords: "办公室, 公司, 会议室, 工作, 写字楼",
  },
  {
    id: "img_park_quiet",
    url: "https://github.com/user-attachments/assets/59b90064-8822-44e2-987d-954a42f2da5b",
    desc: "安静的公园长椅，周围有树木，适合发呆",
    keywords: "公园, 自然, 休息, 长椅, 户外",
  },
  {
    id: "img_sexual_stream",
    url: "https://github.com/user-attachments/assets/2b20015a-cb44-416f-9b2b-ab5164235b2d",
    desc: "不正经的网黄直播平台",
    keywords: "网黄, 直播间，情色直播",
  },
  {
    id: "img_cocktail_bar",
    url: "https://github.com/user-attachments/assets/54c8b933-a596-4fb0-a4c1-c0827b920aad",
    desc: "环境清幽的酒吧",
    keywords: "高端, 酒吧",
  },
  {
    id: "img_old_street",
    url: "https://github.com/user-attachments/assets/3b48118f-c52d-4109-9546-7fef38f64c44",
    desc: "一座海滨城市的旧城区居民区街景",
    keywords: "旧城区, 居民区, 街道, 海滨城市, 古旧",
  },
  {
    id: "img_tech_company",
    url: "https://github.com/user-attachments/assets/9d50fe02-d5c6-4be6-a6c2-3c2fc4c04684",
    desc: "新城区的科技公司聚集地",
    keywords: "互联网公司, 科技公司, 新城区, 堵车, 上班族",
  },
  {
    id: "img_city_center",
    url: "https://github.com/user-attachments/assets/626fd109-a115-46b3-bd97-d3f7f26f8a72",
    desc: "市中心CBD，城市中最繁荣的商业区",
    keywords: "CBD, 商业区, 商圈, 闹市区, 繁华",
  },
  {
    id: "img_high_end_restaurant",
    url: "https://github.com/user-attachments/assets/91aca5a1-6bee-483a-b171-042a4da3d9f9",
    desc: "高档餐厅",
    keywords: "高级, 法餐, 西餐",
  },
  {
    id: "img_studio",
    url: "https://github.com/user-attachments/assets/d408f807-9348-4de7-8915-2977f166cbea",
    desc: "工作室，可用于音乐、设计等工作场景，有各种专业设备",
    keywords: "工作, 音乐, 设计, 设备, 个人工作室",
  },
  {
    id: "img_small_apartment",
    url: "https://github.com/user-attachments/assets/2367aa30-af1b-421b-b95b-c8e585a8f06a",
    desc: "正常的出租屋，有床、桌子、厨房等常规家具",
    keywords: "出租屋, 公寓, 租房",
  },
  {
    id: "img_lab",
    url: "https://github.com/user-attachments/assets/f322b344-ab66-4d0f-aac6-2a0d5a852a84",
    desc: "实验室",
    keywords: "高端, 精密仪器, 无菌环境, 玻璃器皿, 冷色调, 极简主义",
  },
  {
    id: "img_greenhouse",
    url: "https://github.com/user-attachments/assets/010ef494-2ccb-4bdc-b7e2-35cd1694cf18",
    desc: "私人庄园植物温室",
    keywords: "玻璃穹顶, 珍稀植物, 湿润空气, 泥土气息, 绿色, 宁静, 自然光",
  },
  {
    id: "img_hospital",
    url: "https://github.com/user-attachments/assets/18f66252-5f30-4ec3-850c-bb39cccb28c9",
    desc: "医院",
    keywords: "惨白灯光, 消毒水味, 输液架, 蓝色排椅, 冰冷瓷砖, 电子屏",
  },
  {
    id: "img_back_alley",
    url: "https://github.com/user-attachments/assets/3a8a19d7-56e7-42cc-81a4-3bb4fefd8190",
    desc: "旧城区后巷",
    keywords: "涂鸦墙, 潮湿柏油路, 积水水洼, 霓虹灯倒影, 垃圾桶, 野猫, 阴影",
  },
  {
    id: "img_livehouse",
    url: "https://github.com/user-attachments/assets/d59ea2ae-ed98-4f58-aad6-bbb823cd5190",
    desc: "Livehouse、演出现场",
    keywords: "舞台强光, 重低音, 汗水味, 呐喊, 黑暗, 镭射灯",
  },
  {
    id: "img_repair_shop",
    url: "https://github.com/user-attachments/assets/73170b29-b762-44d5-8586-49038d530f3c",
    desc: "机车修理店、汽修店",
    keywords: "机油味, 金属零件, 工具散落, 轮胎, 油污地面, 机械噪音, 卷帘门",
  },
  {
    id: "img_fast_food_shop",
    url: "https://github.com/user-attachments/assets/51025fa5-2a83-4e77-a38e-681143e9717f",
    desc: "快餐店、炸鸡店",
    keywords:
      "炸鸡, 油炸香气, 橙色灯光, 塑料桌椅, 油腻地板, 嘈杂人声, 托盘, 玻璃门",
  },
  {
    id: "img_old_factory",
    url: "https://github.com/user-attachments/assets/d0b78f2f-e66c-4026-94ae-9002327566a7",
    desc: "废弃工厂天台",
    keywords: "生锈栏杆, 空旷, 风声, 远处的城市天际线, 涂鸦墙, 碎石, 夕阳余晖",
  },
  {
    id: "img_campus_corner",
    url: "https://github.com/user-attachments/assets/b9ac31c1-b414-42f3-bd8b-8c0419452f63",
    desc: "高中校园天台/角落",
    keywords: "铁丝网, 课间铃声, 蓝色天空, 涂鸦课桌, 秘密基地, 风",
  },
  {
    id: "img_night_river",
    url: "https://github.com/user-attachments/assets/7d1fce26-064e-4734-b352-752199a7db5b",
    desc: "夜晚的河边/江边堤岸",
    keywords: "水流声, 潮湿空气, 鹅卵石, 芦苇荡, 夜晚",
  },
  {
    id: "img_morning_river",
    url: "https://github.com/user-attachments/assets/a2705788-e8ab-4264-9c5d-c02bf99879d3",
    desc: "白天的河边/江边堤岸",
    keywords: "水流声, 潮湿空气, 鹅卵石, 芦苇荡, 白天",
  },
  {
    id: "img_villa_public_space",
    url: "https://github.com/user-attachments/assets/19c818a5-78d5-4a7e-8f10-5de11718c8cf",
    desc: "别墅、公共客厅",
    keywords: "布艺沙发, 开放式空间, 暖色灯光, 明亮, 抱枕",
  },
  {
    id: "img_interview_room",
    url: "https://github.com/user-attachments/assets/c58a03e9-e4a3-43d3-be14-87a49127ec72",
    desc: "采访室/单人后采间",
    keywords: "纯色背景, 聚光灯, 摄像机, 单人高脚凳, 隔音墙",
  },
  {
    id: "img_high_end_seaview_restaurant",
    url: "https://github.com/user-attachments/assets/91aca5a1-6bee-483a-b171-042a4da3d9f9",
    desc: "海景落地窗餐厅",
    keywords: "长条餐桌, 精致摆盘, 鲜花, 窗外海景, 烛光, 正式晚餐",
  },
  {
    id: "img_supermarket",
    url: "https://github.com/user-attachments/assets/f0a3c620-8f94-4eb4-af6c-4cace2e91d09",
    desc: "超市采购区",
    keywords: "购物车, 货架, 生活用品, 食材, 烟火日常",
  },
  {
    id: "img_home_theater",
    url: "https://github.com/user-attachments/assets/f1980ad5-ad91-481e-964a-7d8d61e4a851",
    desc: "多媒体影音室、电影房、游戏房",
    keywords: "投影仪, 懒人沙发, 遮光窗帘, 电影海报, 昏暗, 独处空间",
  },
  {
    id: "img_car",
    url: "https://github.com/user-attachments/assets/9d652563-6328-4213-bc47-0a056a2970dc",
    desc: "车、车内空间",
    keywords: "狭窄空间, 密闭环境, 导航屏幕, 车载音乐, 沿途风景",
  },
  {
    id: "img_garden_pool",
    url: "https://github.com/user-attachments/assets/8fd24740-7111-4669-b909-c9609f298a8e",
    desc: "别墅露天泳池/花园",
    keywords: "别墅, 度假酒店, 躺椅, 氛围灯带, 波光粼粼, 烧烤架, 夜晚凉风",
  },
  {
    id: "img_university_1",
    url: "https://github.com/user-attachments/assets/4630e3bb-39e9-4083-a901-f0a054e5716b",
    desc: "大学校园1",
    keywords: "教学楼，银杏，人工湖",
  },
  {
    id: "img_university_2",
    url: "https://github.com/user-attachments/assets/294533cb-3d8a-46c9-a464-0a76d8d400e6",
    desc: "大学校园2",
    keywords: "教学楼，图书馆，食堂，樱花，人工湖",
  },
  {
    id: "img_high_school_1",
    url: "https://github.com/user-attachments/assets/eecb8594-ae25-4a01-bc25-56bd3f78ea3f",
    desc: "私立高中校园",
    keywords: "教学楼，食堂，操场，篮球场",
  },
  {
    id: "img_high_school_2",
    url: "https://github.com/user-attachments/assets/81670664-b6dd-44ce-a9b3-6075bb8bc656",
    desc: "体制内高中校园",
    keywords: "红旗，银杏树，教学楼，食堂，操场，篮球场",
  },
  {
    id: "img_high_school_2",
    url: "https://github.com/user-attachments/assets/81670664-b6dd-44ce-a9b3-6075bb8bc656",
    desc: "体制内高中校园",
    keywords: "红旗，银杏树，教学楼，食堂，操场，篮球场",
  },
  {
    id: "img_border_area",
    url: "https://github.com/user-attachments/assets/6f613cf9-5717-4960-8820-445cb498fe16",
    desc: "边境/三不管地带",
    keywords: "法外，蛮荒，边境小镇，废弃工业区，公海游轮，热带雨林，罪恶",
  },
  {
    id: "img_office",
    url: "https://files.catbox.moe/czxw29.png",
    desc: "工位",
    keywords: "写字楼，办公室，工位，办公桌",
  },
  {
    id: "img_villa",
    url: "https://files.catbox.moe/4kobl6.png",
    desc: "别墅内部",
    keywords: "别墅，客厅，高端，复式，落地窗",
  },
  {
    id: "img_concert",
    url: "https://files.catbox.moe/hns9ir.png",
    desc: "演唱会",
    keywords: "演唱会，演出，乐队，人山人海",
  },
  {
    id: "img_ancient_imperial_court",
    url: "https://files.catbox.moe/6pwxwu.png",
    desc: "中国古代朝堂",
    keywords: "朝堂，上朝",
  },
  {
    id: "img_ancient_bedroom",
    url: "https://files.catbox.moe/ejfdfp.png",
    desc: "中国古代寝宫",
    keywords: "寝宫",
  },
  {
    id: "img_museum",
    url: "https://files.catbox.moe/4owk8q.png",
    desc: "博物馆",
    keywords: "博物馆",
  },
  {
    id: "img_art_gallery",
    url: "https://files.catbox.moe/1mmd2f.png",
    desc: "美术馆",
    keywords: "美术馆",
  },
  {
    id: "img_art_exhibition",
    url: "https://files.catbox.moe/7v1sqz.png",
    desc: "艺术展",
    keywords: "艺术展，画展，抽象艺术",
  },
];
